drop table user_coctails;
drop table cocktaile_feedback;
drop table barmen_feedback;
drop table cocktail_ingredient;
drop table ingredient;
drop table cocktail;
drop table user;
drop table user_state;
drop table ROLE;
